// Generated by CoffeeScript 1.7.1
(function() {
  var camera, cameralib, channel, dataurl, notificationLED, tessel, uuid;

  tessel = require('tessel');

  dataurl = require('./dataurl.js');

  cameralib = require('camera-vc0706');

  camera = cameralib.use(tessel.port['B'], {
    resolution: 'qqvga'
  });

  channel = 'tesseldemo';

  uuid = tessel.deviceId();

  notificationLED = tessel.led[3];

  camera.on('ready', function() {
    var PUBNUB;
    PUBNUB = require("pubnub").init({
      publish_key: "demo",
      subscribe_key: "demo",
      uuid: uuid
    });
    console.log("camera ready");
    return setInterval(function() {
      notificationLED.high();
      return camera.takePicture(function(err, image) {
        if (err) {
          return console.log('error taking image', err);
        } else {
          notificationLED.low();
          console.log("sending image");
          return PUBNUB.publish({
            channel: channel,
            message: {
              uuid: uuid,
              ts: new Date().toISOString(),
              image: dataurl.format({
                data: image,
                mimetype: "image/jpg"
              })
            },
            callback: function() {
              return console.log("image sent");
            }
          });
        }
      });
    }, 15000);
  });

  camera.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
