// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, climate, climatelib, tessel, uuid;

  tessel = require('tessel');

  climatelib = require('climate-si7020');

  climate = climatelib.use(tessel.port['D']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  climate.on('ready', function(version) {
    console.log('Ready to read climate sensor');
    return setInterval(function() {
      return climate.readTemperature(function() {
        var temp_args;
        temp_args = arguments;
        return climate.readHumidity(function() {
          var humid_args;
          humid_args = arguments;
          console.log("Temp in C : ", JSON.stringify(temp_args[1].toFixed(4)), " ", "Humidity: ", JSON.stringify(humid_args[1].toFixed(4)), "%RH");
          return PUBNUB.publish({
            channel: channel,
            message: {
              temperature: temp_args,
              humidity: humid_args
            }
          });
        });
      });
    }, 2000);
  });

  climate.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
