// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, servo, servo1, servolib, tessel, uuid;

  tessel = require('tessel');

  servolib = require('servo-pca9685');

  servo = servolib.use(tessel.port['A']);

  servo1 = 1;

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  servo.on('ready', function() {
    var position;
    console.log('Activating Servo');
    position = 0;
    return servo.configure(servo1, 0.05, 0.12, function() {
      return setInterval(function() {
        console.log('Position in range 0-1: ', position);
        PUBNUB.publish({
          channel: channel,
          message: {
            position: position
          }
        });
        servo.move(servo1, position);
        if (position === 0) {
          return position = 1;
        } else {
          return position = 0;
        }
      }, 4000);
    });
  });

}).call(this);
