// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, gps, gpslib, tessel, uuid;

  tessel = require('tessel');

  gpslib = require('gps-a2235h');

  gps = gpslib.use(tessel.port['C']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  gps.on('ready', function(version) {
    var publish;
    console.log('Ready to read GPS');
    publish = function(type) {
      return function(data) {
        console.log(['got', type, JSON.stringify(data)].join("\t"));
        return PUBNUB.publish({
          channel: channel,
          message: {
            type: type,
            data: data
          }
        });
      };
    };
    gps.on('coordinates', publish('coordinates'));
    gps.on('altitude', publish('altitude'));
    gps.on('fix', publish('fix'));
    return gps.on('dropped', publish('dropped'));
  });

  gps.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
