// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, pubnub, relay, relaylib, tessel, uuid;

  tessel = require('tessel');

  relaylib = require('relay-mono');

  relay = relaylib.use(tessel.port['A']);

  PUBNUB = require("pubnub");

  channel = process.argv[2];

  uuid = tessel.deviceId();

  pubnub = PUBNUB.init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  relay.on('ready', function(version) {
    console.log('Connected to relays!');
    return pubnub.subscribe({
      channel: channel,
      message: function(data) {
        return data.forEach(x)(function() {
          relay.toggle(x, function(err) {});
          if (err) {
            return console.log("Error toggling " + x + ": ", err);
          }
        });
      }
    });
  });

  relay.on('latch', function(outlet, value) {
    return console.log('latch on relay outlet ' + outlet + ' switched to ', value);
  });

}).call(this);
