// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, servo, servo1, servolib, tessel, uuid;

  tessel = require('tessel');

  servolib = require('servo-pca9685');

  servo = servolib.use(tessel.port['A']);

  servo1 = 1;

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  servo.on('ready', function() {
    var position;
    console.log('Activating Servo');
    position = 0;
    return servo.configure(servo1, 0.05, 0.12, function() {
      console.log('Position in range 0-1: ', position);
      return PUBNUB.subscribe({
        channel: channel,
        message: function() {
          console.log(JSON.stringify(arguments));
          position = Number(arguments[0]);
          return servo.move(servo1, position);
        }
      });
    });
  });

}).call(this);
