// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, ir, irlib, tessel, uuid;

  tessel = require('tessel');

  irlib = require('ir-attx4');

  ir = irlib.use(tessel.port['A']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  ir.on('ready', function(version) {
    console.log('Ready to read IR sensor...');
    return ir.on('data', function(data) {
      console.log('IR:', data.toString());
      return PUBNUB.publish({
        channel: channel,
        message: {
          ir: data.toString()
        }
      });
    });
  });

  ir.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
