// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, pubnub, relay, relaylib, tessel, uuid;

  tessel = require('tessel');

  relaylib = require('relay-mono');

  relay = relaylib.use(tessel.port['A']);

  PUBNUB = require("pubnub");

  channel = process.argv[2];

  uuid = tessel.deviceId();

  pubnub = PUBNUB.init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  relay.on('ready', function(version) {
    console.log('Connected to relays!');
    return setInterval(function() {
      relay.toggle(1, function(err) {
        if (err) {
          return console.log("Error toggling 1: ", err);
        }
      });
      return relay.toggle(2, function(err) {
        if (err) {
          return console.log("Error toggling 2: ", err);
        }
      });
    }, 2000);
  });

  relay.on('latch', function(outlet, value) {
    console.log('latch on relay outlet ' + outlet + ' switched to ', value);
    return pubnub.publish({
      channel: channel,
      message: {
        outlet: outlet,
        value: value
      }
    });
  });

}).call(this);
