// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, ble, blelib, channel, tessel, uuid;

  tessel = require('tessel');

  blelib = require('ble-ble113a');

  ble = blelib.use(tessel.port['A']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  ble.reset();

  ble.on('ready', function() {
    console.log('Scanning...');
    return ble.startScanning();
  });

  ble.on('discover', function(peripheral) {
    console.log('discover:', peripheral.toString());
    return PUBNUB.publish({
      channel: channel,
      message: {
        peripheral: JSON.parse(peripheral.toString())
      }
    });
  });

}).call(this);
