// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, channel, rfid, rfidlib, tessel, uuid;

  tessel = require('tessel');

  rfidlib = require('rfid-pn532');

  rfid = rfidlib.use(tessel.port['A']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  rfid.on('ready', function(version) {
    console.log('Ready to read RFID card');
    return rfid.on('data', function(card) {
      console.log('UID:', card.uid.toString('hex'));
      return PUBNUB.publish({
        channel: channel,
        message: {
          uid: card.uid.toString('hex')
        }
      });
    });
  });

  rfid.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
