// Generated by CoffeeScript 1.8.0
(function() {
  var PUBNUB, channel, ir, irlib, led1, led2, pubnub, tessel, uuid;

  tessel = require('tessel');

  irlib = require('ir-attx4');

  PUBNUB = require("pubnub");

  ir = irlib.use(tessel.port['A']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  led1 = tessel.led[0].output(1);

  led2 = tessel.led[1].output(0);

  pubnub = PUBNUB.init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  ir.on('ready', function(version) {
    console.log('Connected to IR!');
    return pubnub.subscribe({
      channel: channel,
      message: function(data) {
        var intVals;
        intVals = data.split(",");
        intVals.forEach(function(x, i) {
          return intVals[i] = parseInt(x, 16);
        });
        return ir.sendRawSignal(38, Buffer(intVals), function(err) {
          if (err) {
            console.log("Unable to send signal: ", err);
          }
          if (!err) {
            return console.log("Signal sent!");
          }
        });
      }
    });
  });

  ir.on('error', function(err) {
    return console.error(err);
  });

  ir.on('data', function(data) {
    return console.log("Received RX Data: ", data.toString('hex'));
  });

}).call(this);
