// Generated by CoffeeScript 1.7.1
(function() {
  var camera, cameralib, channel, notificationLED, tessel, uuid;

  tessel = require('tessel');

  cameralib = require('camera-vc0706');

  camera = cameralib.use(tessel.port['B'], {
    resolution: 'qqvga'
  });

  channel = process.argv[2];

  uuid = tessel.deviceId();

  notificationLED = tessel.led[3];

  camera.on('ready', function() {
    var PUBNUB;
    PUBNUB = require("pubnub").init({
      publish_key: "demo",
      subscribe_key: "demo",
      uuid: uuid
    });
    console.log("camera ready");
    notificationLED.high();
    return camera.takePicture(function(err, image) {
      var image_string;
      if (err) {
        console.log('error taking image', err);
      } else {
        notificationLED.low();
        image_string = image.toString('hex');
        console.log("sending image", image_string);
        PUBNUB.publish({
          channel: channel,
          message: {
            image: image_string
          }
        });
      }
      return camera.disable();
    });
  });

  camera.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
