// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, ambient, ambientlib, channel, conn, tessel, uuid;

  tessel = require('tessel');

  ambientlib = require('ambient-attx4');

  ambient = ambientlib.use(tessel.port['A']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  conn = function() {
    ambient.on('ready', function(version) {
      console.log('Ready to read ambient sensor');
      return setInterval(function() {
        ambient.setLightTrigger(0.5);
        return ambient.on('light-trigger', function(data) {
          PUBNUB.publish({
            channel: channel,
            message: {
              type: "Light detected!",
              data: data
            }
          });
          ambient.clearLightTrigger();
          return setTimeout(function() {
            return ambient.setLightTrigger(0.1);
          }, 1500);
        });
      });
    });
    return ambient.on('error', function(err) {
      return console.error(err);
    });
  };

  setTimeout(conn, 1000);

}).call(this);
