// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, accel, accellib, channel, tessel, uuid;

  tessel = require('tessel');

  accellib = require('accel-mma84');

  accel = accellib.use(tessel.port['A']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  accel.on('ready', function(version) {
    console.log('Ready to read accelerometer');
    accel.removeAllListeners('data');
    return accel.setOutputRate(0.5, function() {
      return accel.on('data', function(xyz) {
        console.log('xyz:', JSON.stringify(xyz));
        return PUBNUB.publish({
          channel: channel,
          message: xyz
        });
      });
    });
  });

  accel.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
