// Generated by CoffeeScript 1.7.1
(function() {
  var PUBNUB, ambient, ambientlib, channel, tessel, uuid;

  tessel = require('tessel');

  ambientlib = require('ambient-attx4');

  ambient = ambientlib.use(tessel.port['A']);

  channel = process.argv[2];

  uuid = tessel.deviceId();

  PUBNUB = require("pubnub").init({
    publish_key: "demo",
    subscribe_key: "demo",
    uuid: uuid
  });

  ambient.on('ready', function(version) {
    console.log('Ready to read ambient sensor');
    return setInterval(function() {
      return ambient.getLightLevel(function() {
        var light_args;
        light_args = arguments;
        return ambient.getSoundLevel(function() {
          var sound_args;
          sound_args = arguments;
          console.log("Light:", JSON.stringify(light_args), " ", "Sound:", JSON.stringify(sound_args));
          return PUBNUB.publish({
            channel: channel,
            message: {
              light: light_args,
              sound: sound_args
            }
          });
        });
      });
    }, 2000);
  });

  ambient.on('error', function(err) {
    return console.error(err);
  });

}).call(this);
